/*
 *  Functions used by pthread implementations
 */

#ifndef SERIAL_FUNC_H
#define SERIAL_FUNC_H

/* Structure of thread_data_t */
typedef struct thread_data_t{
	int q_limit, d_limit, antidiag, k;
	char* q;
	char* d;
	int** score_matrix;
	int mv;
}thread_data_t;

/*
 *  Function: make_args
 *  -------------------
 * 
 *  Makes a thread_data_t item to be inserted to the thread pool
 * 
 *  Input: Values a thread needs to calculate the inner loop of our serial code
 * 
 *  Returns: thread_data_t* tdata
 */
extern thread_data_t* make_args(int antidiag, int k, char* q, char* d,\
						 int** score_matrix);

/*
 *  Function: inner
 *  ---------------
 * 
 *  Calculation of the value of the k-cell in the antidiagonal 
 * 
 *  Input: thread_data_t* args, generated by make_args()
 * 
 */
extern void * inner(void*);

extern int calculate_score(int** score_matrix, int match, int mismatch, \
						   int gap,	int threads, char* q, char* d, \
						   MVP* *max_score, double *calc_time);

#endif
